import React from 'react';
import Modal from 'react-modal';
import { ImCross } from "react-icons/im";

const TermsAndConditionModal = ({modalIsOpen,setTermModal}) =>{


    const customStyles = {
        content : {
          top        : '50%',
          left       : '50%',
          transform   : 'translate(-50%, -50%)'
        }
      };


       return(
           <div>
            <Modal
                isOpen={modalIsOpen}
                contentLabel="Example Modal"
                style={customStyles}
                ariaHideApp={false}
            >
                <div className="terms-modal-header">
                        <h3>Terms And Condition</h3>
                        <ImCross
                            onClick={() =>setTermModal(false)}
                        />
                </div>
                <div className="terms-main-content">
                    <h1>Terms and Conditions</h1>
                    <p className="notice">Notice for Japanese Residents, United States Residents and Malaysian Residents ONLY</p>
                    <p>Please note that due to respective local regulations, we do not accept registrations from residents of Japan, United States of America & Malaysia. Further we do not accept registrations if you are using or accessing KaigenXchange Services on behalf of an entity that is incorporated, established, or domiciled in Japan, the United States of America or Malaysia.</p>
                    <p>-------------------------------------</p>
                    <h4>TERMS AND CONDITIONS </h4>
                    <p>These Terms and Conditions (“Terms and Conditions”) and any terms expressly incorporated herein apply to your access to and/or use of any services made available by KaigenX Pte Ltd, a company incorporated and organized under the laws of India (“K-genxchange”) through K-genxchange.exchange (“Website”), mobile applications and/or APIs/Developer Tools and any other related services provided by K-genxchange, including the Platform and the Services (“K-genxchange Services”).</p>
                    <p>The terms “we”, “us” and “our” refer to K-genxchange and its Affiliates and related companies.</p>
                    <p>We reserve the right to modify these Terms and Conditions at any time and/or when required by law. We will notify Users of any changes to these Terms and Conditions by email (sent to the email address as specified in your Account) and/or by means of a notice published on the Platform. Such modifications will be effective and binding on you upon posting such modifications onto the Platform or such other timing as K-genxchange may specify in writing. You acknowledge that it is your responsibility to check for notifications regularly and the updated Terms and Conditions upon such notifications. You further agree that any notification of modifications in the manner as aforesaid shall be sufficient notice to you and your continued access to and/or use of the K-genxchange Services following the notification of any modifications to these Terms and Conditions indicates your acceptance of any such modifications.</p>
                    <p>These Terms and Conditions constitute a binding agreement between you and K-genxchange. By clicking a checkbox or a button that contains words such as “I Agree” when these Terms and Conditions are presented to you or, if earlier, by accessing or using the K-genxchange Services, you agree to be bound by, and to comply with, these Terms and Conditions. If you do not accept these Terms and Conditions, you must stop accessing and/or using the K-genxchange Services. The <span>Privacy Policy</span> and <span>Cookies Policy</span> and all other applicable rules, policies and procedures posted on the Platform constitute a part of and are hereby incorporated by reference in their entirety into these Terms and Conditions.</p>
                    <h4>1.General Terms</h4>
                    <p>K-genxchange provides a digital platform (the “Platform”) enabling the storage, transfer, obtaining, exchanging and trading of certain crypto and fiat currencies (hereinafter the “Services”).</p>
                    <h4>2.Eligibility</h4>
                    <p>You represent and warrant that you are not listed on the Monetary Authority of India’s Lists of Designated Individuals and Entities, on any trade or economic sanctions lists, such as the UN Security Council Sanctions list, designated as a “Specially Designated National” by OFAC (Office of Foreign Assets Control of the U.S. Treasury Department) nor placed on the U.S. Commerce Department’s “Denied Persons List”.</p>
                    <p>Your place of residence determines the availability of the certain functions of the K-genxchange Services. It is your sole responsibility to get informed about those rules and regulations in your place of residence and any other applicable laws and to abide by them.</p>
                    <h4>(a) Individuals</h4>
                    <p>You agree and understand that by accessing, or using the K-genxchange Services, you have affirmed that you are at least 18 years old, have the legal capacity to consent to these Terms and Conditions, and agree to be bound by the policies and practices of these Terms and Conditions in their entirety.</p>
                    <h4>(b) Institutions</h4>
                    <p>If you represent a legal entity (“Institution”), you affirm that you, as an individual, are an authorized representative of the Institution with the full power and authority to enter into and bind the Institution to these Terms and Conditions, and the Institution has full power and authority to enter into and be bound by these Terms and Conditions. By accepting these Terms and Conditions, you are accepting them on behalf of the Institution. In these Terms and Conditions, “you” and “yourself” include both you and such Institution.</p>
                    <h4>3.Fees </h4>
                    <p>You agree to pay all fees described herein or otherwise posted on the Platform, as may be updated by K-genxchange at its sole discretion from time to time. Any updates to fees will apply prospectively to any trades or transactions that take place on the Platform following the effective date of such updates. You hereby authorize K-genxchange to deduct from your Account any applicable fees owed by you to K-genxchange under these Terms and Conditions and you agree that K-genxchange shall be entitled to set-off against any payment due from or payable to K-genxchange hereunder, any sums you are obliged to pay or credit to K-genxchange hereunder and K-genxchange may by notice to you reduce any fees or any other charges, sums or monies due or payable to you hereunder by any amounts you are obliged to pay or credit to Woowoo hereunder.</p>
                    <p>You are solely responsible for any fees charged by third parties in connection with your use of the K-genxchange Services, including without limitation fees charged by financial institutions in connection with your transfer or attempted transfer of Legal Tender or from an External Bank Account.</p>
                    <h4>4.Risk Disclosure</h4>
                    <p>You should be aware that the risk of loss in trading or holding Digital Currencies can be substantial. By using the Services, you accept all risks of acquiring, trading, holding or otherwise transacting with Digital Currencies through the Services (including Digital Currencies Transactions). You may lose Digital Currencies, your Digital Currencies may lose some or all of their value, you may be unable to acquire, transfer, trade, lend or access Digital Currencies, you may, as a result of your trading activities, owe Digital Currencies greater than the amount available in your Account and you may suffer other types of financial loss. You should not acquire any Digital Currencies unless you can afford to lose the entire value of those Digital Currencies.</p>
                    <p>You are responsible for making an independent evaluation of the merits and risks, and the security, integrity, operation and platform of any Digital Currencies that you decide to acquire or trade. You represent and warrant that you have sufficient knowledge, experience, understanding and information to make such evaluations and have taken such professional advice as you deem necessary.</p>
                    <h4>5.Definitions</h4>
                    <p>“Account” or “K-genxchange Account” means an individual or corporate account on the Platform to use the Services.</p>
                    <p>“Affiliate” means in relation to a party, any company, partnership, trust or other entity directly or indirectly controlled by, controlling or under common control with that party, where “control” or its derivatives or variants for the purpose of this definition shall mean with regard to an party, the legal, beneficial or equitable ownership, directly or indirectly, of fifty percent (50%) or more of the issued capital or voting rights (or other ownership interest, if not a corporation) of such entity, or the equivalent right under contract or otherwise, to control or cause the direction of management and policy decisions of such entity with regard to relevant subjects.</p>
                    <p>“Business Day” means a day on which banks are open for general banking business in India (not being a Saturday, Sunday or public holiday in India).</p>
                    <p>“Digital Currency”or“Digital Currencies” means a digital representation of value based on (or built on top of) a cryptographic protocol of a computer network (including without limitation those referred to as “cryptocurrency”, “token”, “virtual currency”, “digital currency” or “virtual commodity”), such as Bitcoin or Ethereum.</p>
                    <p>“Digital Currency Transactions” means the following types of transaction involving a Digital Currency and undertaken on the Platform: (i) the transfer of Digital Currencies into a User’s Account; (ii) the withdrawal of Digital Currencies from a User’s Account; and (iii) the trading of Digital Currencies for Legal Tender or other Digital Currencies.</p>
                    <p>“External Bank Account” means an account in your name at a financial institution from or to which you intend to transfer or transfer Legal Tender.</p>
                    <p>“Funds” means, in relation to each User, the balance of Digital Currencies and/or Legal Tender, as the context requires, in such User’s Account.</p>
                    <p>“Legal Tender” means a currency designated as legal tender in a particular country or jurisdiction, such as India Rupees.</p>
                    <p>“Legal Tender Transaction” means the following types of transaction involving Legal Tender and undertaken on the Platform: (i) the transfer of Legal Tender into a User’s Account; (ii) the withdrawal of Legal Tender from a User’s Account; and (iii) the trading of Legal Tender for Digital Currency(ies).</p>
                    <p>“Order” means a request by a User on the Platform to buy or sell the relevant Approved Currencies.</p>
                    <p>“Password” means, in relation to each User, the valid password that such User may use in conjunction with the relevant Username to access and/or use the Services.</p>
                    <p>“Trade” or “Trading” means the acquisition or disposition of Approved Currencies by a User in exchange for other Approved Currencies or Legal Tender of another User on the Platform.</p>
                    <p>“User” refers to a registered user of the Services.</p>
                    <p>“Username” means, in relation to each User, the unique login identification name or code which identifies such User.</p>
                    <h4>6.Account Registration & Requirements</h4>
                    <h4>(a) Registration</h4>
                    <p>In order to access and/or use the Services, you will need to register for an account on the Platform (an “Account” or a “K-genxchange Account”) by providing your full legal name and email address, as well as accept these Terms and Conditions, our Privacy Policy and Cookies Policy and all other applicable rules, policies and procedures. You agree to provide complete and accurate information when registering for an Account and agree to promptly update any information you provide to K-genxchange so that such information is complete and accurate at all times. K-genxchange may, in its sole discretion, refuse to open an Account for you.</p>
                    <p>If you request to create an Account, a Username and Password may either be: (a) determined by and issued to you by K-genxchange; or (b) provided by you and accepted by Woowoo in its sole discretion, in connection with the access to and/or use of the Services. K-genxchange may at any time, in its sole discretion, forthwith invalidate the Username and/or Password without giving any reason or prior notice and without prejudice to other provision in these Terms and Conditions, K-genxchange shall not be held liable for any damage, loss or harm arising out of such invalidation. The Username and Password is for each User’s personal use only and neither may be transferred to any other person or entity.</p>
                    <h4>(b) User Identity Verification</h4>
                    <p>You agree to provide us with the information we request for the purposes of identity verification and the detection of money laundering, terrorist financing, fraud or any other financial crime and permit us to keep a record of such information. You will need to complete certain certification procedures before you are permitted to use the Services and your access to one or more Services, and the limits that apply to your use of the Services, may be altered as a result of information collected on an ongoing basis. The information we request may include certain personal information, including but not limited to, your name, address, telephone number, email address, date of birth, taxpayer identification number, government identification number, and information regarding your bank account (including the name of the bank, account type, routing number and account number). In providing us with this or any other information that may be required, you confirm that the information is accurate and authentic. You agree to keep us updated if any of the information you provide changes. If there is any reasonable doubt that any information provided by you is wrong, untruthful, outdated or incomplete, K-genxchange shall have the right to send you a notice to demand corrections, remove relevant information directly and, as the case may be, terminate all or part of the Services to you. You shall be solely and fully responsible for any loss or expenses incurred during the use of the Services if you cannot be reached through the contact information provided.</p>
                    <p>The information we collect is used for the detection of money laundering, terrorist financing, fraud and other financial crimes on the Platform. We will collect, use and share this information in accordance with our Privacy Policy. In addition to providing this information, to facilitate compliance with global industry standards for data retention, you agree to permit us to keep a record of such information for the lifetime of your Account plus five (5) years beyond the closing of your Account.</p>
                    <p>BY SIGNING UP FOR AN ACCOUNT YOU HEREBY AUTHORIZE K-genxchange TO MAKE INQUIRIES, WHETHER DIRECTLY OR THROUGH THIRD PARTIES, THAT K-genxchange CONSIDERS NECESSARY TO VERIFY YOUR IDENTITY OR PROTECT YOU AND/OR K-genxchange AGAINST FRAUD OR OTHER FINANCIAL CRIMES, AND TO TAKE ACTION K-genxchange REASONABLY DEEMS NECESSARY BASED ON THE RESULTS OF SUCH INQUIRIES. YOU ALSO ACKNOWLEDGE AND AGREE THAT YOUR PERSONAL INFORMATION MAY BE DISCLOSED TO CREDIT REFERENCE AND FRAUD PREVENTION OR FINANCIAL CRIME AGENCIES AND THAT THESE AGENCIES MAY RESPOND TO OUR INQUIRIES IN FULL.</p>
                    <h4>(c) Account Security </h4>
                    <p>K-genxchange strives to maintain the safety of those user funds entrusted to us and has implemented industry standard protections for the Services. In a bid to provide a safe trading environment and advanced security for every K-genxchange Account, K-genxchange has in place a two-factor authentication process which is mandatory for every User to enable. In the event a User disables the two-factor authentication process for any reason whatsoever, the User must re-enable the two-factor authentication process before using the Services.</p>
                    <p>However, there are risks that are created by individual user actions. You agree to consider your access credentials such as Username and Password as confidential information and not to disclose such information to any third party. You also agree that you alone are responsible for taking necessary safety precautions to protect your own Account and personal information.</p>
                    <p>You shall be solely responsible for the safekeeping of your K-genxchange Account and the relevant Username and Password on your own, and you shall be fully responsible for all instructions, requests, transactions and activities under such K-genxchange Account (whether authorised by you or not), and K-genxchange shall not be under any duty to investigate, enquire into or ascertain whether any such instructions, requests, transactions or activities are authorized, authentic, legal, valid or enforceable or whether any transaction or the underlying contract connected with such transaction is void or voidable, or whether any transaction is permitted under the applicable terms and conditions governing the relevant Approved Currency (if any). K-genxchange shall be entitled to assume that all activities are authorised, authentic, legal, valid and enforceable (as the case may be), that all transactions and the underlying contracts connected with such transactions are not void or voidable, and that all transactions are permitted under the applicable terms and conditions governing the relevant Approved Currency (if any), and K-genxchange shall be under no duty to reject, reverse, adjust or modify any instruction, request, transaction or activity by reason that it was not legal, valid or enforceable, that any transaction or the underlying contract connected with such transaction is void or voidable, or that any transaction is not permissible under the applicable terms and conditions governing the relevant Approved Currency (if any). K-genxchange will not be responsible for any loss or consequences of authorized or unauthorized access and/or use of your Account credentials (including Username and Password) including but not limited to information disclosure, information posting, consent to or submission of various rules and agreements by clicking on the Website, online renewal of agreement, etc.</p>
                    <p>By creating an Account, you hereby agree that: </p>
                    <p>(i) you will notify K-genxchange immediately if you are aware of any unauthorized access and/or use of your K-genxchange Account and the relevant Username and Password by any person or entity or any other violations to the security rules or breach of security;</p>
                    <p>(ii) you will strictly observe the security, authentication, dealing, charging, withdrawal mechanism or procedures of the Platform and/or Service;</p>
                    <p>(iii) you will log out from the Platform by taking proper steps at the end of every visit;</p>
                    <p>(iv) any access or use (or purported access or use) of the Platform and any information, data, instructions or communications referable to your Username and Password shall be deemed to be, as the case may be: (a) access or use of the Platform by you; and/or (b) information, data, instructions or communications carried out, transmitted or validly issued by you. K-genxchange shall be entitled (but not obliged) to act upon, rely on and/or hold you solely responsible and liable in respect thereof as if the same were carried out, transmitted or validly issued by you. You further agree and acknowledge that you shall be solely responsible for and bound by any access or use of the Platform, any information, data, instructions or communications referable to your Username and Password, and any activity that takes place under your Account, whether authorised by you or not.</p>
                    <p>(v) you authorise K-genxchange to perform the Services in the manner described in these Terms and Conditions and other applicable terms and conditions;</p>
                    <p>(vi) any records created and maintained by K-genxchange of the information, data, instructions, communications, transactions or operations made or performed, processed or effected through the Platform or in relation to Platform, Accounts, Approved Currencies and/or Legal Tender by you or any other User or any person purporting to be you or such other User, acting on behalf or purportedly acting on behalf of you or such other User, shall be binding on you or such other User for all purposes whatsoever and shall be conclusive evidence of such information, data, instructions, communications, transactions or operations;</p>
                    <p>(vii) the Funds available in your Account as determined by K-genxchange from its records shall, save for manifest error, be deemed to be conclusive and binding against you; and</p>
                    <p>(viii) you will honour all Orders placed through your Account and all transactions executed involving your Account.</p>
                    <h4>7.Know-Your-Client (“KYC”), Anti-Money Laundering and Counter Terrorism Financing (“AML/CTF”) </h4>
                    <p>K-genxchange reserves the right to perform due diligence checks on you pursuant to any regulatory requirements, and requests for you to provide such documentation/information as may be necessary to satisfy itself of your identity, and the purposes of use of the K-genxchange Services (“Customer Due Diligence”). Such Customer Due Diligence may include and are not limited to taking enhanced due diligence measures on politically exposed persons and/or customers which present a higher risk for money laundering or terrorism financing as will be determined by K-genxchange’s internal guidelines. K-genxchange further reserves the right to impose certain trading limits on you where K-genxchange have not yet conducted any Customer Due Diligence on. In connection therewith, K-genxchange reserves the right to suspend and/or terminate your Account if you fail to comply or cooperate with K-genxchange or fail to satisfy in relation to the due diligence checks and/or requests under this Clause 7. Further, K-genxchange reserves the right to file suspicious transaction reports in confidentiality to the relevant government agencies.</p>
                    <p>As at 1 September 2019, K-genxchange partners with <span>Cynopsis Solutions</span> for the "Know Your Customer" process. As such, please also refer to the Cynopsis Solutions <span>Terms</span> and <span>Privacy Policy</span> for further information.</p>
                    <h4>8.Currencies</h4>
                    <p>K-genxchange will in its sole discretion determine which types of Digital Currencies and Legal Tender will be supported for transfer, storage, lending, trading or any other activities through the Services (collectively, “Currencies”). K-genxchange gives no assurances that any Digital Currency which is the subject of a fork (hard, soft, velvet or otherwise) will be supported through the Services.</p>
                    <p>Among the Currencies, the specific Currencies that you are permitted to transfer, store, trade or otherwise interact with through the Services are referred to as ““Approved Currencies”. When you access the Services, only transactions involving Approved Currencies will be available to you. The Approved Currencies available to you are based on the jurisdiction of which you are a citizen or resident and any other factors determined by K-genxchange in its sole discretion. The Approved Currencies available to you may differ from the Approved Currencies available to other Users.</p>
                    <p>Without notice and for any reason, K-genxchange may suspend, discontinue or terminate support for a Currency on the Services, remove a Currency from the list of Approved Currencies or otherwise suspend or terminate your ability to withdraw, transfer, trade, store or otherwise interact with any Approved Currency. However, K-genxchange will use commercially reasonable efforts to notify you at least 14 days (where practicable) prior to taking any action that would permanently (or for such duration as K-genxchange may determine at its sole discretion) prevent you from withdrawing the affected Funds from your Account. If you do not withdraw the affected Funds from your Account before your access to an applicable Currency through the Service is suspended or terminated, then you may irrevocably lose your ability to withdraw, transfer, trade, store or otherwise access or control the affected Funds. K-genxchange will not be liable to you for any loss, liability or expenses related to its decision to suspend, discontinue or terminate support for a Currency on the Services, remove a Currency from the list of Approved Currencies or otherwise suspend or terminate your ability to withdraw, transfer, trade, store or otherwise interact with any Currency.</p>
                    <h4>9.Digital Currency Services</h4>
                    <p>You represent and warrant that you will comply with the terms and conditions governing the relevant Approved Currencies (if any) and all terms and conditions applicable to any Digital Currency wallets that you use to transfer Approved Currencies to or from your K-genxchange Account. K-genxchange is not responsible for the management and security of any such wallets or the failure of any transfer of Approved Currencies between your K-genxchange Account and such Digital Currency wallets (including where such transaction is not supported by such Digital Currency wallets).</p>
                    <p>The value of Digital Currencies which Users transfer to K-genxchange does not earn any interest, and K-genxchange does not carry any specific insurance in relation to such Digital Currencies.</p>
                    <h4>(a) Digital Currency Transactions</h4>
                    <h4>(i) Transfer of Approved Currencies into K-genxchange Account </h4>
                    <p>Subject to applicable laws, the availability of the Services and any other limitations or conditions contained in these Terms and Conditions, on the Website or of the Platform or otherwise (including Digital Currencies and the sending and receiving Digital Currency wallets), you may at any time transfer one or more Approved Currencies from your Digital Currency wallet into your Account by sending such amount of Approved Currencies to the receiving addresses designated by K-genxchange to you from time to time for the relevant Approved Currencies (“Digital Currency Address”). Your K-genxchange Account balance will be updated to reflect such quantity of Approved Currencies received by K-genxchange at the relevant Digital Currency Address. The Approved Currencies that are reflected in your K-genxchange Account balance at any time will be located at Digital Currency Addresses (or such replacement addresses) owned and managed by K-genxchange, and such Digital Currencies may be held by K-genxchange together with K-genxchange’s own Digital Currencies and those of other Users. K-genxchange and/or its third party service provider store and manage the Digital Currency private keys associated with such Digital Currency Addresses, which are necessary for Digital Currency Transactions to be approved. You will not have access to such private keys. K-genxchange and/or its third party service provider may store such private keys and related information in a combination of online and offline storage. You acknowledge that the retrieval of information from offline storage may delay the initiation, processing or execution of Digital Currency Transactions, as further set out in Clause 9(c) below.</p>
                    <h4>(ii) Withdrawal of Approved Currencies from K-genxchange Account</h4>
                    <p>Subject to applicable laws, the availability of the Services and any other limitations or conditions contained in these Terms and Conditions, on the Website or of the Platform or otherwise (including Digital Currencies and the sending and receiving wallets), you may submit a request on the Platform to withdraw balance Digital Currencies from your Account at any time to any of your designated Digital Currency wallet addresses.</p>
                    <p>You hereby authorized K-genxchange to transfer the type and amount of Approved Currencies specified by you from your Account to your designated Digital Currency wallet addresses specified by you at the time of the submission of the relevant withdrawal request and to deduct any fees applicable to such withdrawal that K-genxchange or its third-party service providers may charge from such transferred amount.</p>
                    <p>Without prejudice to Clause 9(c), as we will manually verify and process all withdrawals of Digital Currencies, we will endeavour to process your withdrawal request within three (3) Business Days. We may suspend the submission and/or processing of withdrawal requests at any time for system maintenance or in any such situations where it is reasonable to do so. For the avoidance of doubt, this shall include a situation where a technical failure arises in the protocol of the relevant Digital Currency.</p>
                    <p>You agree that it is your sole responsibility to provide us with the accurate withdrawal details (i.e. withdrawing Digital Currency wallet address) when submitting your request to withdraw your balance Digital Currencies from your Account. K-genxchange is not able to reverse any transfers. Without prejudice to other provision in these Terms and Conditions, you agree that K-genxchange shall not be held liable for any claims, losses or damages which may arise as a result of your failure to receive the Digital Currencies which you have withdrawn, due to your provision of any incorrect and/or outdated withdrawal details.</p>
                    <h4>(iii)Transmission Delays</h4>
                    <p>K-genxchange makes no guarantee regarding the amount of time it may take to complete any Digital Currency Transaction. K-genxchange and/or its third party service provider store Digital Currency private keys associated with Digital Currency Addresses, in a combination of online and offline storage, and such private keys are the means by which we can securely execute a Digital Currency Transaction. As a result of our security protocols, it may be necessary for us to retrieve private keys or related information from offline storage in order to facilitate and process a Digital Currency Transaction in accordance with your instructions, and you acknowledge that this may delay the initiation, debiting and crediting or execution of such Digital Currency Transaction. Without prejudice to other provision in these Terms and Conditions, you agree and acknowledge that K-genxchange shall not be held liable for any claims, losses or damages which may arise from such delays.</p>
                    <h4>(iv) Incorrect Transactions</h4>
                    <p>You agree that it is your sole responsibility to ensure that any Digital Currency Transaction which you undertake shall be accurate, well-formatted and denominated in the correct cryptocurrency. Without prejudice to other provision in these Terms and Conditions, you agree that K-genxchange shall not be held liable for any claims, losses or damages arising as a result of any incorrect transfers, withdrawals, Orders, Trades and/or other transactions made through the Services.</p>
                    <h4>10.Legal Tender Transactions (where applicable)</h4>
                    <p>External Bank Accounts must be in your name and not the name of a third party. K-genxchange may limit the number of External Bank Accounts that you may designate to be associated with your K-genxchange Account. You are solely responsible for your use of any External Bank Account, and you represent and warrant that you will comply with all terms and conditions applicable to any External Bank Account that you use to transfer Legal Tender to or from your K-genxchange Account. K-genxchange is not responsible for the management and security of any External Bank Account or the failure of any transfer of Legal Tender between your K-genxchange Account and an External Bank Account (including where such transaction is not supported by the External Bank Account).</p>
                    <p>As at 1 September 2019, such transfer of Legal Tender between an External Bank Account and your K-genxchange Account will be powered by Xfers. As such, please also refer to the XFERS Terms of Service and Privacy Policy for further information.</p>
                    <p>The value of Legal Tender which Users transfer to K-genxchange does not earn any interest and K-genxchange does not carry any specific insurance in relation to such Legal Tender</p>
                    <h4>(a) Transfer of Legal Tender into K-genxchange Account</h4>
                    <p>Subject to applicable laws, the availability of the Services and any other limitations or conditions contained in these Terms and Conditions, on the Website or of the Platform or otherwise, you may at any time initiate a transfer of Legal Tender from your External Bank Account into your K-genxchange Account. Your K-genxchange Account balance will be updated to reflect such amount of Legal Tender received by K-genxchange in the relevant bank account designated by K-genxchange.</p>
                    <h4>(b) Withdrawal of Legal Tender from K-genxchange Account</h4>
                    <p>Subject to applicable laws, the availability of the Services and any other limitations or conditions contained in these Terms and Conditions, on the Website or of the Platform or otherwise, you may submit a request on the Platform to withdraw balance Legal Tender from your K-genxchange Account at any time to a External Bank Account at any time.</p>
                    <p>You hereby authorize K-genxchange to transfer the type and amount of Legal Tender specified by you from your K-genxchange Account to a verified external bank account specified by you at the time of the submission of the relevant withdrawal request via the Services and to deduct any fees applicable to such withdrawal. K-genxchange or its third-party service providers may charge from such transferred amount.</p>
                    <p>You agree that it is your sole responsibility to provide us with the accurate withdrawal details (i.e. External Bank Account) when submitting your request to withdraw your balance Legal Tender from your K-genxchange Account. K-genxchange is not able to reverse any transfers. Without prejudice to other provision in these Terms and Conditions, you agree that K-genxchange shall not be held liable for any claims, losses or damages which may arise as a result of your failure to receive the Legal Tender which you have withdrawn, due to your provision of any incorrect and/or outdated withdrawal details.</p>
                    <h4>(c) Transmission Delays</h4>
                    <p>K-genxchange makes no guarantee regarding the amount of time it may take to complete any Legal Tender Transaction, which is dependent on a variety of factors, including the performance of third parties responsible for maintaining the applicable External Bank Account.</p>
                    <h4>(d)Incorrect Transactions</h4>
                    <p>You agree that it is your sole responsibility to ensure that any Legal Tender Transaction which you undertake shall be accurate, well-formatted and denominated in the correct currency. Without prejudice to other provision in these Terms and Conditions, you agree that K-genxchange shall not be held liable for any claims, losses or damages arising as a result of any incorrect transfers, withdrawals, Orders, Trades and/or other transactions made through the Services.</p>
                    <h4>11.Trading</h4>
                    <h4>(a) Funds</h4>
                    <p>If your Account has been opened and activated, and you have sufficient Funds in your Account, you will be able to engage in Trading on the Platform. You will be required to maintain in your Account a sufficient balance of the applicable Funds to satisfy any open Orders, your required margin and applicable fees. If you have an insufficient amount of Funds in your Account to fulfill an Order, K-genxchange may cancel the entire Order or may fulfil an Order partially to the extent it can be covered by the Funds in your Account (after deducting any fees payable to K-genxchange in connection with the Trade).</p>
                    <h4>(b) Orders</h4>
                    <p>To initiate a Trade, you must submit an Order. Once you have submitted an Order, we will attempt to match your Order with another Order submitted by another User. We are under no obligation to match any Order submitted by you, and we maintain sole discretion over whether any Order is matched and whether any Trade is executed. There will be no contract between you and another User until the Order has been matched and a Trade has been executed.</p>
                    <p>Further to the above, you agree that: (i) it is your sole responsibility to ensure the accuracy of each Order submitted through your Account; and (ii) you, and for all purposes all Users shall be deemed to have, have personal knowledge of every Order placed through your/their Account(s).</p>
                    <h4>(c) Counterparty</h4>
                    <p>If your Order is successfully matched with the Order submitted by another User, and a Trade has been executed (including where we have not exercised our discretion to prevent that Order from being fulfilled), such User shall become your counterparty to the executed Trade (your “Counterparty”). K-genxchange therefore does not serve as a central counterparty in such executed Trades entered between you and your Counterparty on the Platform, and does not have any contractual relationship with you and/or your Counterparty in relation to such executed Trades. Notwithstanding the above, K-genxchange reserves the right to trade on the Platform as a User and upon execution of such Trade, as a Counterparty but you acknowledge and agree that in all other cases, whenever a transaction takes place between you and other User(s) on the Platform, K-genxchange does not act as an intermediary but only provides a platform to complete the transaction(s) between the two parties, the buyer and the seller. We match all Users anonymously and do not provide Users with information about their Counterparties.</p>
                    <p>You hereby authorize K-genxchange to transfer the relevant type and amount of Approved Currencies or Legal Tender (as the case may be) from your Account to your Counterparty’s Account for the purpose of settling the Trade between you and your Counterparty, and to deduct any fees applicable to such transfer and settlement that K-genxchange or its third-party service providers may charge from your Funds.</p>
                    <h4>(d)Trading Hours</h4>
                    <p>Generally, trading on the Platform will trade continuously from 0000hrs to 2359hrs on every day of the year. We may suspend trading and/or access to the Platform at any time for system maintenance or for other reasons such as maintaining an orderly market. Without prejudice to other provision in these Terms and Conditions, in the event of such suspension of trading, you agree that K-genxchange shall not be held liable for any claims, losses or damages arising as a result of any suspension of trading on the Platform pursuant to this Clause 11(d).</p>
                    <h4>(e) Suspension of Trading</h4>
                    <p>As part of K-genxchange’s goal to maintain an orderly market, K-genxchange shall be entitled at its sole and absolute discretion to suspend trading on the Platform, in the event of any market disruption or any other relevant external events which may disrupt the trading on the Platform (e.g. hacking of the Platform). Without prejudice to other provision in these Terms and Conditions, in the event of such suspension of trading, you agree that K-genxchange shall not be held liable for any claims, losses or damages arising as a result of any suspension of trading on the Platform pursuant to this Clause 11(e).</p>
                    <h4>12.API/Developer Tools</h4>
                    <p>K-genxchange may make available certain public or authenticated development applications through the Services, including without limitation K-genxchange’s application programming interface and any accompanying or related documentation, source code, executable applications and other materials, and any other resources or services available on the Website (“API/Developer Tools”). Please refer to terms and conditions on API/Developer Tools contained on the Website.</p>
                    <h4>13.NO FINANCIAL ADVICE / Potential Risks </h4>
                    <p>K-genxchange is not your broker, intermediary, agent or advisor and has no fiduciary relationship or obligation to you in connection with any Trades or any other transactions, decisions or activities carried out by you using the K-genxchange Services.</p>
                    <p>K-genxchange does not provide legal, financial, trading, tax or any other kind of specialised or expert advice in connection with any Digital Currencies or any Trades or other transactions, decisions or activities carried out by you using the K-genxchange Services. No communication or information provided to you by K-genxchange is intended to or shall be considered or construed as advice. You understand that any recommendations or commentary made by K-genxchange or its employees or representatives or other Users should be considered general in nature and you must use your own judgment or seek the advice of an expert before taking any action as a result of any such recommendation or commentary. K-genxchange gives no assurances as to the accuracy, reliability, performance, fitness for purpose, satisfactory quality, timeliness or completeness of any such recommendation or commentary.</p>
                    <p>By using the K-genxchange Services, you confirm that you have understood and that you accept the risks associated with Digital Currencies and Digital Currency Transactions, including without limitation, the following:</p>
                    <p>(a) Digital Currencies are highly volatile assets and are based on their respective decentralized monetary protocols which are still in its experimental stage and may be subject to substantial changes at any time. Any malfunction, flaws, breakdown or abandonment of any a decentralized monetary protocol may have a material adverse effect on the relevant Digital Currencies. Furthermore, developments in cryptographic technologies and techniques or changes in consensus protocol or algorithms could present risks to the relevant Digital Currencies;</p>
                    <p>(b) The trading of Digital Currencies may be subject to market risk that investment performance of the relevant cryptocurrencies cannot be predicted or guaranteed, and that any decisions you make to trade in Digital Currencies as facilitated by this Platform or the Services will be based solely on your own evaluation of your financial circumstances, investment objectives, risk tolerance, liquidity needs and any other factors that you deem relevant. You should pay close attention to your positions, and how you may be impacted by sudden and adverse shifts in trading and other market activities;</p>
                    <p>(c) The trading of Digital Currencies exposes you to operational risk. This is the risk that you may suffer a loss because of a malfunction or disruption of the Services, arising from scheduled or unscheduled downtimes, matching system failure, database failure, Digital Currencies transfer or storage failure, failure or malfunction of the API, hacker attacks or other attacks by malicious groups or organisations which may attempt to interfere with Digital Currencies, Orders and/or Trades or steal Digital Currencies or other failures or malfunctions;</p>
                    <p>(d) The holding and/or trading of Digital Currencies may expose you to regulatory risk. This is the risk that you may suffer a loss pursuant to the restriction or termination of certain aspects of the Services in response to existing regulations or future regulatory changes or actions. Further to the above, the legal status of some cryptocurrencies may be uncertain. Users shall be solely responsible for understanding the regulation and/or legal treatment of the relevant cryptocurrencies under the applicable law;</p>
                    <p>(e) the tax treatment and accounting of Digital Currencies is uncertain and may vary amongst jurisdictions. Users shall be solely responsible for obtaining independent tax advice in connection with Trades, which may result in adverse tax consequences; and</p>
                    <p>(f) Digital Currencies may only be accessed with a combination of private key and password. Loss of requisite private key(s) associated with the relevant Digital Currency Addresses may result in the loss of the relevant Digital Currencies which will be unrecoverable and permanently lost.</p>
                    <h4>14.Account Termination, Suspension or Restriction </h4>
                    <p>You may terminate your Account at any time and for whatever reason upon giving us written notice of such termination, by contacting <span>support@K-genxchange.exchange</span>.</p>
                    <p>In connection therewith, K-genxchange reserves the right to seek all remedies available at law and/or in equity for violations of these Terms and Conditions and other applicable terms and conditions.</p>
                    <p>You agree and accept that: (i) K-genxchange can suspend, restrict or terminate your Account, and/or deny or limit your access to your Account and/or the K-genxchange Services at its sole discretion without providing any explanations and without prior notice, including the grounds as set out below; and (ii) K-genxchange’s decision to take certain actions, including but not limited to limiting access to, suspending, or terminating your Account, may be based on confidential criteria that are essential to K-genxchange’s risk management and security protocols, and (iii) K-genxchange is under no obligation to disclose the details of its risk management and security procedures to you or any other Users:</p>
                    <p>(a) when the activity from or attributable to your Account violates applicable laws, these Terms and Conditions and/or other applicable terms and conditions and/or infringes the intellectual property rights of K-genxchange or any relevant third parties;</p>
                    <p>(b) a subpoena, court order, or binding order of a government authority on the subject has been issued in relation to you or your Account;</p>
                    <p>(c) there have been actual or suspected attempts by you to access the K-genxchange Services in an unauthorized way and/or assisting others in such unauthorized access;</p>
                    <p>(d) there have been actual or suspected attempts by you to break the security features of the software comprised in K-genxchange Services and/or taking advantage of such breaches;</p>
                    <p>(e) there have been actual or suspected attempts by you to use the K-genxchange Services for any illegal or unlawful activities, including but not limited to money laundering, illegal gambling, terrorism, etc.);</p>
                    <p>(f) your Account is subject to any pending litigation, investigation, or government proceeding and/or K-genxchange perceives a heightened risk of legal or regulatory non-compliance associated with such Account;</p>
                    <p>(g) your action(s) amount to circumventing K-genxchange’s controls, including, but not limited to, opening multiple Accounts or abusing promotions which K-genxchange may offer from time to time;</p>
                    <p>(h) you failed to, avoided or delayed in making any fee payments;</p>
                    <p>(i) you have abused or threatened other Users and/or K-genxchange staff;</p>
                    <p>(j) there have been actual or suspected attempts by User to manipulate the market and/or raise the trading volume artificially; and/or</p>
                    <p>(k) there has been a request of the law enforcement institution or a government agency.</p>
                    <p>K-genxchange reserves the right to undertake any necessary technical and/or legal measures to prevent any User’s access to and/or use of such User’s Account and/or the K-genxchange Services, if K-genxchange suspect threats or abuses to its intellectual property and violations of these Terms and Conditions.</p>
                    <p>You understand that if your Account is unconfirmed or inactive (i.e. have not been confirmed, accessed and/or used for 12 months or longer), such Account will also be terminated by K-genxchange. It shall solely be each User’s responsibility to ensure Funds in the unconfirmed or inactive Account have been withdrawn. Without prejudice to other provision in these Terms and Conditions, K-genxchange shall not be held liable for terminating such unconfirmed or inactive Accounts, irrespective of the Funds remaining in such Accounts.</p>
                    <p>The suspension, restriction or termination of your Account may result in the cancellation of any Orders that you have submitted and the unwinding of any Trades and/or positions that you have entered into. We expressly exclude any liability for the losses and/or profits you would have made as a result of any cancellation of Orders, unwinding of Trades, early closure of your positions or your suspension or restriction from trading on the Platform and you agree to fully indemnify, defend and hold harmless the Platform, K-genxchange, its Affiliates, related companies and their directors, shareholders, officers, employees, agents, licensors, third party service providers, and any other third party providing service to K-genxchange in relation to the Services whether directly or indirectly, from and against any and all losses, liabilities, claims, damages, costs and expenses (including legal fees, and any fines, fees or penalties imposed by any regulatory authority) arising out of or related to third party action resulting from your conduct, any cancellation of Orders, unwinding of Trades, any early closure of your positions or your suspension or restriction from trading on the Platform by K-genxchange.</p>
                    <p>Whilst your Account is suspended, K-genxchange may conduct investigations and may require you to cooperate with its enquiries. During the investigation stage, you will not be able to make transfers or withdrawals to or from your Account nor will you be able to Trade or submit Orders. At the end of the investigation, K-genxchange may, at its sole discretion, decide to close your Account for which K-genxchange is not required to provide you with any reasons for the same.</p>
                    <p>You acknowledge and agree that your Account can be blocked due to inability and/or denial to provide the required identification documents and/or any other data necessary for the Customer Due Diligence procedure and/or for any other reason.</p>
                    <p>The termination of an Account for any reason shall not affect obligations, rights or liabilities which have accrued or may accrue as at the date of termination or thereafter and any obligations which are intended to survive the termination of an Account whether or not such survival is specified herein.</p>
                    <p>In case of any concerns and/or questions related to the termination procedure please contact us via <span>support@K-genxchange.exchange.</span></p>
                    <h4>15.Representations and Warranties</h4>
                    <p>You hereby represent and warrant to and undertake with K-genxchange that:</p>
                    <p>(a) You are authorized to access and use the K-genxchange Services. In particular, the jurisdiction where you reside, hold citizenship or conduct business allows you to utilise the Services;</p>
                    <p>(b) You are not a United States resident;</p>
                    <p>(c) You are over 18 years old and have full legal capacity to enter into these Terms and Conditions;</p>
                    <p>(d) Without prejudice to the generality of the foregoing, you satisfy, and will on an ongoing basis satisfy, the eligibility requirements as set out in Clause 2 of these Terms and Conditions;</p>
                    <p>(e) You are the legal and beneficial owner of the Approved Currencies that you have transferred/are transferring into your Account;</p>
                    <p>(f) All the Approved Currencies transferred into your Account have been derived from legitimate/legal sources;</p>
                    <p>(g) The access and/or use of the K-genxchange Services do not infringe or violate any local law of your country of residence;</p>
                    <p>(h) You will only apply for and hold a single Account with us;</p>
                    <p>(i) (If you are using the K-genxchange Services as an individual) You are not acting on someone else’s behalf;</p>
                    <p>(j) (If you are using the K-genxchange Services on behalf of or for the benefit of an Institution) You are an authorized representative of the Institution with the full power and authority to enter into and bind the Institution to these Terms and Conditions, and the Institution has full power and authority to enter into and be bound by these Terms and Conditions, and you are authorised to transact on behalf of the organisation or corporate entity and the Institution will be liable for your actions including any breach of this Agreement; and</p>
                    <p>(k) You understand the risks associated with trading in a cryptocurrency exchange and you agree that the use of the K-genxchange Services is at your own risk. You agree that K-genxchange is not liable for any damage, loss or harm arising out of your access and/or use of the K-genxchange Services.</p>
                    <p>You agree that: </p>
                    <p>(a) The information provided on the K-genxchange Services is for general information purposes only and is given in good faith. The information should not be construed as a recommendation to trade or engage the Service provided by K-genxchange in a particular manner. Nothing in the K-genxchange Services shall be construed as an offer to sell or a solicitation of an offer to purchase any securities where it would be illegal to do so;</p>
                    <p>(b) Notwithstanding the fact that K-genxchange administers the Services and runs the Platform, you understand and agree that K-genxchange may also trade as a User on the Platform;</p>
                    <p>(c) You shall cooperate with K-genxchange and provide such necessary documents and/or information as may be requested by K-genxchange as part of the Customer Due Diligence process and/or the relevant investigations as may be performed by K-genxchange;</p>
                    <p>(d) K-genxchange gives no warranty about the K-genxchange Services. Without limitation to the foregoing, K-genxchange does not warrant that the K-genxchange Services will meet your requirements, that it will be suitable for your purposes, accurate, reliable or correct or that the K-genxchange Services will be available any particular time or location, and K-genxchange does not warrant that any defects or errors will be corrected. For the avoidance of doubt, all statutory or implied conditions or warranties are excluded unless otherwise prohibited under applicable laws, including any warranties of title, non-infringement of third party rights, merchantability or satisfactory quality;</p>
                    <p>(e) K-genxchange does not warrant that the K-genxchange Services and access and/or use thereof will be uninterrupted, timely, secure or error free. Among other things, the operation and availability of the systems used for accessing the K-genxchange Services, computer equipment/networks (which may be provided by a third party) and the Internet, can be unpredictable and may from time to time interfere with or prevent access to the K-genxchange Services. Without prejudice to other provision in these Terms and Conditions, you agree that K-genxchange shall not be held liable in any way for any such interference that prevents your access or use of the K-genxchange Services; and</p>
                    <p>(f) K-genxchange may, from time to time and without giving any reason or prior notice, upgrade, modify, suspend or discontinue the provision of or remove the K-genxchange Services (or part thereof), and shall not be liable if any such upgrade, modification, suspension or discontinuation prevents any User from accessing the K-genxchange Services (or part thereof).</p>
                    <p>Notwithstanding other provisions in these Terms and Conditions, K-genxchange warrants that when it trades as a User on the Platform, it shall at all times trade in good faith with the relevant Users and refrain from doing any act which might either directly or indirectly give rise to a conflict of interest with such Users, always provided that nothing in this Clause 14 will prevent K-genxchange from carrying out its normal business activities on behalf of itself where no such conflict exists.</p>
                    <p>Accordingly, you agree to assume full responsibility and risk of loss resulting from your use of the K-genxchange Services.</p>
                    <p>You undertake not to: </p>
                    <p>(a) use or upload any software or material that contains, or which you have reason to suspect contains, computer virus or other malicious, destructive or corrupting code, agent, program or macros;</p>
                    <p>(b) upload or transmit any materials through the Platform which are or may be illegal, misleading, erroneous, objectionable, defamatory, harassing, abusive, harmful, pornographic, “x-rated” or obscene content;</p>
                    <p>(c) use the Platform other than in conformance with the acceptable use policies of any connected computer networks, any applicable Internet standards and any other applicable laws; or</p>
                    <p>(d) impersonate any person or entity or to falsely state or otherwise misrepresent your affiliation with any person or entity.</p>
                    <h4>16.LIMITATION OF LIABILITY AND INJUNCTIVE RELIEF</h4>
                    <p>THE USER UNDERSTANDS AND EXPRESSLY AGREES THAT UNLESS OTHERWISE PROHIBITED UNDER APPLICABLE LAWS, IN NO EVENT WILL K-genxchange, ITS AFFILIATES, RELATED COMPANIES OR ANY OF THEIR OFFICERS, EMPLOYEES, DIRECTORS, EMPLOYEES, SHAREHOLDERS, AGENTS, LICENSORS, THIRD PARTY SERVICE PROVIDERS, AND ANY OTHER THIRD PARTY PROVIDING SERVICE TO K-genxchange IN RELATION TO THE K-genxchange SERVICES WHETHER DIRECTLY OR INDIRECTLY, BE LIABLE TO THE USER OR ANYONE ELSE UNDER ANY THEORY OF LIABILITY (WHETHER IN CONTRACT, TORT, STATUTORY, OR OTHERWISE) FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF FUNDS, REVENUES, PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SUCH PARTIES WERE ADVISED OF, KNEW OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY ACCESS AND/OR USE OF THE K-genxchange SERVICES OR THE USER’S USE OF THE ACCOUNT REGISTERED TO SUCH USER, OR THE USE OF ANYONE USING AN ACCOUNT REGISTERED TO THE USER, OR ANY UNAUTHORIZED USE OF THE USER’S ACCOUNT OR ANY PARTS THEREOF AND INCLUDING:</p>
                    <ul>
                        <li>THE ACCURACY AND COMPLETENESS OF THE CONTENT COMPRISED IN ANY K-genxchange SERVICES;</li>
                        <li>THE ACCURACY AND COMPLETENESS OF THE CONTENT ON THE THIRD PARTY SITES LINKED TO ANY K-genxchange SERVICES (BY MEANS OF HYPERLINKS, BANNER ADS, ETC.);</li>
                        <li>THE SERVICES OR THE SERVICES AVAILABLE ON ANY THIRD PARTY SITES LINKED TO THE PLATFORM (BY MEANS OF HYPERLINKS, BANNER ADS, ETC.);</li>
                        <li>PERSONAL INJURIES OR PROPERTY DAMAGES OF ANY KIND;</li>
                        <li>THIRD-PARTY CONDUCT OF ANY NATURE WHATSOEVER, INCLUDING ANY BREACH OF OR DELAY OR FAILURE OF ANY USER TO COMPLY WITH THESE TERMS AND CONDITIONS;</li>
                        <li>ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SERVERS AND/OR CONTENT, INFORMATION (E.G. PERSONAL, FINANCIAL, ETC.) AND THE STORED DATA;</li>
                        <li>ANY INTERRUPTION OF THE SERVICES OR THE SERVICES AVAILABLE ON ANY OTHER SITES LINKED TO THE PLATFORM (BY MEANS OF HYPERLINKS, BANNER ADS, ETC.);</li>
                        <li>ANY VIRUSES, WORMS, BUGS, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR FROM THE PLATFORM OR ANY SITES LINKED TO THE PLATFORM (BY MEANS OF HYPERLINKS, BANNER ADS, ETC.);</li>
                        <li>ANY OBJECTIONABLE, DEFAMATORY, HARASSING, ABUSIVE, HARMFUL, PORNOGRAPHIC, “X-RATED”, OBSCENE, ETC. CONTENT;</li>
                        <li>ANY SUSPENSION, INTERRUPTION OR CLOSURE OF THE PLATFORM;</li>
                        <li>ANY TECHNICAL, SYSTEM, SERVER OR CONNECTION FAILURE, ERROR, OMISSION INTERRUPTION OR DELAY IN TRANSMISSION; AND</li>
                        <li>ANY TECHNICAL AND/OR SYSTEM FAILURE OF THE PLATFORM.</li>
                    </ul>
                    <p>WITHOUT PREJUDICE TO THE FOREGOING, THE USER ACKNOWLEDGES AND AGREES THAT ANY CAUSE OF ACTION RELATED TO THE USE OF THE K-genxchange SERVICES OUGHT TO BE COMMENCED WITHIN 12 MONTHS FROM THE TIME THE CAUSE OF THE ACTION HAS ARISEN. OTHERWISE, SUCH CAUSE OF ACTION WILL BE BARRED PERMANENTLY.</p>
                    <p>WITHOUT PREJUDICE TO THE FOREGOING, THE USER EXPRESSLY ACCEPTS AND AGREES THAT IN NO EVENT WILL K-genxchange’S TOTAL AGGREGATE LIABILITY FOR ANY AND ALL CLAIMS, SUITS, DEMANDS, ACTIONS OR OTHER LEGAL PROCEEDINGS UNDER, ARISING OUT OF OR RELATING TO THESE TERMS AND CONDITIONS OR RELATING TO OR ARISING IN CONNECTION WITH THE K-genxchange SERVICES, WHETHER BASED ON AN ACTION OR EVENT OR SERIES OF CONNECTED ACTIONS OR EVENTS ARISING FROM THE SAME FACTUAL ACT OR OMISSION, IN CONTRACT, NEGLIGENCE, TORT OR OTHERWISE, SHALL EXCEED THE TOTAL TRANSACTION FEE PAID BY THE USER TO K-genxchange FOR THE PARTICULAR SERVICE(S) THAT ARE SUBJECT TO THE CAUSE OF ACTION. THE FOREGOING LIMITATION OF LIABILITY APPLIES, UNLESS OTHERWISE PROHIBITED UNDER APPLICABLE LAWS, AND WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THESETERMS AND CONDITIONS, OR THE ACCESS OR USE OF THE K-genxchange SERVICES.</p>
                    <p>IT IS HEREBY ACKNOWLEDGED AND EXPRESSLY AGREED BY THE USER THAT K-genxchange OR THE PLATFORM IS NOT LIABLE FOR ANY TRANSACTIONS INITIATED BY THE USER ON THE PLATFORM.</p>
                    <p>NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN, THE USER HEREBY IRREVOCABLY WAIVES ANY RIGHT OR REMEDY TO SEEK AND/OR OBTAIN INJUNCTIVE OR OTHER EQUITABLE RELIEF OR ANY ORDER WITH RESPECT TO, AND/OR TO ENJOIN OR RESTRAIN OR OTHERWISE IMPAIR IN ANY MANNER, THE PRODUCTION, DISTRIBUTION, EXHIBITION OR OTHER EXPLOITATION OF ANY OF K-genxchange OR ANY OF ITS AFFILIATE OR RELATED COMPANY OR RELATED SERVICES, OR THE USE, PUBLICATION OR DISSEMINATION OF ANY ADVERTISING IN CONNECTION WITH SUCH SERVICES.</p>
                    <p>THE USER EXPRESSLY AGREES TO FULLY INDEMNIFY, DEFEND AND HOLD HARMLESS THE PLATFORM, K-genxchange, ITS AFFILIATES, RELATED COMPANIES AND THEIR DIRECTORS, OFFICERS, EMPLOYEES, SHAREHOLDERS, AGENTS, LICENSORS, THIRD PARTY SERVICE PROVIDERS, AND ANY OTHER THIRD PARTY PROVIDING SERVICE TO K-genxchange IN RELATION TO THE SERVICES WHETHER DIRECTLY OR INDIRECTLY, FROM AND AGAINST ANY AND ALL LOSSES, LIABILITIES, CLAIMS, DAMAGES, COSTS AND EXPENSES (INCLUDING LEGAL FEES, AND ANY FINES, FEES OR PENALTIES IMPOSED BY ANY REGULATORY AUTHORITY) ARISING OUT OF OR RELATED TO YOUR BREACH OF THESE TERMS AND CONDITIONS ASSERTED AGAINST OR INCURRED BY K-genxchange THAT RISE OUT OF, RESULT FROM, OR MAY BE PAYABLE BY VIRTUE OF, ANY BREACH OR NON-PERFORMANCE OF ANY TERMS OF THESE TERMS AND CONDITIONS INCLUDING ANY REPRESENTATION, WARRANTY, COVENANT OR AGREEMENT MADE OR OBLIGATION TO BE PERFORMED BY THE USER PURSUANT TO THESE TERMS AND CONDITIONS OR YOUR VIOLATION OF ANY APPLICABLE LAW, RULE OR REGULATION OR THE RIGHTS OF ANY THIRD PARTY. THIS CLAUSE WILL SURVIVE ANY TERMINATION OR EXPIRATION OF THESE TERMS AND CONDITIONS, OR THE ACCESS OR USE OF THEK-genxchange SERVICES.</p>
                    <h4>17.Force Majeure</h4>
                    <p>Without prejudice to other provision in these Terms and Conditions, K-genxchange and/or the Platform shall not be liable for any failure to perform any of its obligations under these Terms and Conditions or provide the K-genxchange Services or any part thereof if the performance is prevented, interrupted or delayed by a Force Majeure Event (defined below) and in such case its obligations shall be suspended for so long as the Force Majeure Event continues.</p>
                    <p>"Force Majeure Event" means any event due to any cause beyond the reasonable control of K-genxchange, including, without limitation, interruption in telecommunications or Internet services or network provider services, breach or virus in the systems, fire, flood, explosion, acts of God, civil commotion, act of civil or military authorities, riots, insurrection, war, acts of government.</p>
                    <h4>18.Governing Law</h4>
                    <p>These Terms and Conditions shall be governed by and construed in accordance with India law.</p>
                    <h4>19.Severability</h4>
                    <p>If any provision of these Terms and Conditions is determined to be illegal, void, invalid or unenforceable by any legislation to which it is subject, in whole or in part under, such illegalilty, voidness, invalidity or unenforceability shall apply only to such provision or part of such provision and the remaining part of such provision and all other provisions of this Agreement shall continue to be in full force and effect.</p>
                    <h4>20.Assignment</h4>
                    <p>You may not assign or transfer any right to access and/or use the K-genxchange Services or any of your rights or obligations under these Terms and Conditions without prior written consent from us, including by operation of law or in connection with any change of control. K-genxchange may assign or transfer any or all of its rights or obligations under these Terms and Conditions, in whole or in part, without notice or obtaining your consent or approval</p>
                    <h4>21.Waiver</h4>
                    <p>The failure or delay of a party to exercise or enforce its rights conferred upon it under these Terms and Conditions or require performance of any provision shall not be deemed to be a waiver of any such rights or operate so as to bar the exercise or enforcement thereof at any subsequent time or times nor shall a waiver of any breach or default of these Terms and Conditions or any provision of these Terms and Conditions constitute a waiver of any subsequent breach or default or a waiver of the provision itself.</p>
                    <h4>22.Third-Party Website Disclaimer</h4>
                    <p>Any links to third-party websites from the Platform and/or Services do not imply endorsement by K-genxchange of any products, services or information presented therein, nor does K-genxchange guarantee the accuracy of the information contained on them. In addition, since K-genxchange has no control over the terms of use or privacy practices of third-party websites, you should read and understand those policies carefully.</p>
                    <h4>23.English Language Controls</h4>
                    <p>Any translation provided is solely for the User’s convenience. The meanings of terms, conditions and representations herein are subject to definitions and interpretation in the English language. Any translation provided may not accurately represent the information in the original English. In case of any difference between the English version and the translated versions of these Terms and Conditions, the English version shall prevail.</p>
                    <h4>24.Headings and Interpretation</h4>
                    <p>The headings and subheadings herein are included for convenience and identification only and are not intended to interpret, define or limit the scope, extent or intent of these Terms and Conditions in any manner whatsoever.</p>
                    <p>The meaning of general words is not limited by specific examples introduced by expressions such as, “including”, “for example”, “such as”, or such similar expressions, and the word “includes” or “including” as used in these Terms and Conditions shall be construed to mean “includes without limitation” or, as the case may be, “including without limitation”.</p>
                    <h4>25.Entire Agreement</h4>
                    <p>These Terms and Conditions constitute the entire agreement, and supersede all prior understandings, oral or written, between the parties regarding the subject of these Terms and Conditions.</p>
                    <h4>26.Support</h4>
                    <p>In the event the User has any concern or questions in relation to any information uploaded on the Website, K-genxchange Services and/or these Terms and Conditions and User’s rights and obligations or with respect to processing of information or use of Website etc., the User may submit a written request to <span>support@K-genxchange.exchange</span>. We shall endeavor to expeditiously redress the same, but within reasonable time as may be provided in applicable laws.</p>
                    <h4>Intellectual Property</h4>
                    <p>K-genxchange grants you a non-transferable, non-exclusive, revocable, limited license to use and access the K-genxchange Services solely for your own personal, informational and non-commercial use, provided that you do not modify the K-genxchange Services and that you retain all copyright and other proprietary notices contained in the K-genxchange Services.</p>
                    <p>K-genxchange or its licensor(s) reserves and retains all rights (including copyrights, trademarks, patents as well as any other intellectual property right) in relation to the K-genxchange Services. You may not do anything that will violate or infringe such intellectual property rights and, in particular, you shall not copy, download, publish, distribute, transmit, disseminate, sell, broadcast, circulate, exploit (whether for commercial benefit or otherwise) or reproduce any of the information or content contained in or provided on or via the K-genxchange Services in any form without the prior written permission of K-genxchange or its licensor(s). Further, no part or parts of the K-genxchange Materials may be reproduced, distributed, republished, displayed, broadcast, hyperlinked, mirrored, framed, transferred or transmitted in any manner or by any means or stored in an information retrieval system without the prior written permission of K-genxchange or its licensor(s).</p>
                    <h4>28.Rights of Third Parties</h4>
                    <p>A person or entity who is not a party to these Terms and Conditions shall have no right under the Contracts (Rights of Third Parties) Act, Chapter 53B of India or other similar laws to enforce any of these Terms and Conditions, regardless of whether such person or entity has been identified by name, as a member of a class or as answering a particular description. K-genxchange’s right to vary these Terms and Conditions may be exercised without the consent of any person or entity who is not a party to these Terms and Conditions. For the avoidance of doubt, nothing in this clause shall affect the rights of any permitted assignee or transferee of these Terms and Conditions.</p>
                    <h4>29.No Internet Access</h4>
                    <p>The User agrees and acknowledges that these Terms and Conditions and the K-genxchange Services do not include the provision of Internet access or other telecommunication services by K-genxchange. Any Internet access or telecommunications services (such as mobile data connectivity) required by any User to access and use the K-genxchange Services shall be such User’s sole responsibility and shall be separately obtained by such User, at his own cost, from the appropriate telecommunications or internet access service provider.</p>
                    <h4>30.Successors and Assigns</h4>
                    <p>hese Terms and Conditions will bind each User and K-genxchange and their respective successors in title and assigns and will continue to bind each User notwithstanding any change in K-genxchange’s name or constitution or K-genxchange’s merger, consolidation or amalgamation with or into any other entity (in which case these Terms and Conditions will bind each User to K-genxchange’s successor entity).</p>
                    <h4>31.Sub-contracting and Delegation</h4>
                    <p>K-genxchange may delegate or sub-contract the performance of any of its functions in connection with the K-genxchange Services.</p>
                </div>
                <div className="terms-modal-footer">
                    {/* <div>
                         <input 
                             type="checkbox" 
                             id="termsandcondition" 
                             name="termsandcondition" 
                             value="termsandcondition" 
                             onChange={() =>props.handleCheckBox('termsandcondition')}
                             checked={props.termsandcondition}
                         />
                         <label htmlFor="termsandcondition">I acknowledge that I have read and agree to KaigenX India's Terms and Conditions.</label>
                    </div>
                     <button
                       onClick={() =>props.termsModal(false)}
                     >Done</button> */}
                </div>
            </Modal>
           </div>
       )
}

export default TermsAndConditionModal